import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Lexome</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>
          Build books better.
        </p>
        <p>
          Lexome is an e-reader built for the future. It delivers a top-quality reading experience
          while unlocking immersive featuring connecting you to an author's world and to the community
          of engaged readers.
        </p>

        <p>
          Context Summaries
          Lexome summaries will update as your progress through 
        </p>

        <p>
          Author Q&A
        </p>

        <p>
          Our text-to-voice service can turn any book into a read-along experience.
        </p>
      </main>
    </>
  );
}
